name: InsomniaDOTA
main: net.insomniacraft.codeex.InsomniaDOTA.InsomniaDOTA
version: 0.1b
description: Plugin that automates and controls DOTA elements of InsomniaCraft DOTA server.
authors: [JazzKr, ninjaturtlez]
website: codeex.insomniacraft.net
commands:
  setup:
   description: Used to trigger setup mode on server to modify weak points.
   usage: Usage is /setup
  set:
   description: Used to set turret and nexus weak points and spawns when setting up server.
   usage: Usage is /set [colour] [structure]
  join:
   description: Player command to join a team.
   usage: Usage is /join
  clear:
   description: Used to clear a block selection during setup.
   usage: Usage is /clear
  rdy:
   description: Used to signal a player is ready so a game can start.
   usage: Usage is /ready
  info:
   description: Used to get information on the state of structures in game.
   usage: Usage is /info [colour] [structure]
  reset:
   description: Used to reset the game.
   usage: Usage is /reset
  all:
   description: Used to talk in all chat.
   usage: Usage is /all
  teamswitch:
   description: Used to switch a player from one team to the other.
   usage: Usage is /teamswitch [player]
  b:
   description: Used to recall.
   usage: Usage is /b
  fb:
   description: Used to spawn a fireball
   usage: Usage is /fb
permissions:
  DOTA.play:
   description: Enables a person to join and play DOTA games.
   default: op
  DOTA.admin:
   description: Enables admins to control various aspects of a DOTA game like resetting or setup.
   default: op